name: auto-format
on: push
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: black
              uses: lgeiger/black-action@master
              with:
                  args: .
            - name: Check for modified files
              id: git-check
              run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
            - name: Push changes
              if: steps.git-check.outputs.modified == 'true'
              run: |
                  git config --global user.name 'NIU Rover'
                  git config --global user.email 'niurover@gmail.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                  git checkout $GITHUB_REF
                  git commit -am "Automated changes"
                  git push origin HEAD:$GITHUB_REF
